### ISSUE TITLE
Consider including console dispatcher

### ISSUE THREAD

**Issue by jcchavezs** [ExpediaDotCom/haystack-agent#71]
Right now there are ways to dispatch haystack data like kafka, kinesis or s3 but if a user wants to easy get started with the agent or **just test if instrumentation is reporting correctly**, having to configure this stuff might be inconvenient. Should we consider including a console dispatcher so quick understandings when it comes to receive spans are easier? I could come up with a PR for this.

**Comment by marcoslopes** [comment]
@jcchavezs could the [LoggerDispatcher](https://github.com/ExpediaDotCom/haystack-client-java/blob/master/core/src/main/java/com/expedia/www/haystack/client/dispatchers/LoggerDispatcher.java) solve that, then will just depends which handler we choose.

**Comment by jcchavezs** [comment]
@marcoslopes I think they are different `Dispatcher`s. The interfaces are different: https://github.com/ExpediaDotCom/haystack-agent/blob/master/api/src/main/java/com/expedia/www/haystack/agent/core/Dispatcher.java vs https://github.com/ExpediaDotCom/haystack-client-java/blob/master/core/src/main/java/com/expedia/www/haystack/client/dispatchers/Dispatcher.java

**Comment by marcoslopes** [comment]
@jcchavezs sorry, I was working with the client and that that context in mind, didn't notice i was on the agent repo. Thanks for pointing that out to me.

**Comment by jcchavezs** [comment]
Closed by https://github.com/ExpediaDotCom/haystack-agent/pull/74
